// Code generated by protoc-gen-dynamodb. DO NOT EDIT.

package messagev1ddbpath

import (
	"reflect"

	"github.com/crewlinker/protoc-gen-dynamodb/ddb/ddbpath"
)

func init() {
	ddbpath.RegisterMessage(reflect.TypeOf(KitchenPath{}), map[string]ddbpath.FieldInfo{
		"1":  {},
		"16": {Ref: reflect.TypeOf(KitchenPath{})},
		"13": {Kind: ddbpath.MapKind, Ref: reflect.TypeOf(AppliancePath{})},
		"19": {Kind: ddbpath.ListKind, Ref: reflect.TypeOf(EnginePath{})},
	})
	ddbpath.RegisterMessage(reflect.TypeOf(EnginePath{}), map[string]ddbpath.FieldInfo{
		"1": {},
	})
	ddbpath.RegisterMessage(reflect.TypeOf(AppliancePath{}), map[string]ddbpath.FieldInfo{
		"1": {},
	})
}
