// Code generated by protoc-gen-dynamodb. DO NOT EDIT.

// Package ddbv1ddb holds generated schema structure
package ddbv1ddb

import expression "github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"

// FieldOptions allows for constructing type-safe expression names
type FieldOptions struct {
	expression.NameBuilder
}

// WithDynamoNameBuilder allows generic types to overwrite the path
func (p FieldOptions) WithDynamoNameBuilder(n expression.NameBuilder) FieldOptions {
	p.NameBuilder = n
	return p
}

// Name appends the path being build
func (p FieldOptions) Name() expression.NameBuilder {
	return p.AppendName(expression.Name("1"))
}

// Pk appends the path being build
func (p FieldOptions) Pk() expression.NameBuilder {
	return p.AppendName(expression.Name("2"))
}

// Sk appends the path being build
func (p FieldOptions) Sk() expression.NameBuilder {
	return p.AppendName(expression.Name("3"))
}

// Omit appends the path being build
func (p FieldOptions) Omit() expression.NameBuilder {
	return p.AppendName(expression.Name("4"))
}

// Set appends the path being build
func (p FieldOptions) Set() expression.NameBuilder {
	return p.AppendName(expression.Name("5"))
}

// Embed appends the path being build
func (p FieldOptions) Embed() expression.NameBuilder {
	return p.AppendName(expression.Name("6"))
}
