// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: ddb/v1/options.proto

package ddbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// encoding kinds
type Encoding int32

const (
	// unspecified encoding
	Encoding_ENCODING_UNSPECIFIED Encoding = 0
	// json encoding
	Encoding_ENCODING_JSON Encoding = 1
	// dynamo encoding
	Encoding_ENCODING_DYNAMO Encoding = 2
)

// Enum value maps for Encoding.
var (
	Encoding_name = map[int32]string{
		0: "ENCODING_UNSPECIFIED",
		1: "ENCODING_JSON",
		2: "ENCODING_DYNAMO",
	}
	Encoding_value = map[string]int32{
		"ENCODING_UNSPECIFIED": 0,
		"ENCODING_JSON":        1,
		"ENCODING_DYNAMO":      2,
	}
)

func (x Encoding) Enum() *Encoding {
	p := new(Encoding)
	*p = x
	return p
}

func (x Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_ddb_v1_options_proto_enumTypes[0].Descriptor()
}

func (Encoding) Type() protoreflect.EnumType {
	return &file_ddb_v1_options_proto_enumTypes[0]
}

func (x Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Encoding) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Encoding(num)
	return nil
}

// Deprecated: Use Encoding.Descriptor instead.
func (Encoding) EnumDescriptor() ([]byte, []int) {
	return file_ddb_v1_options_proto_rawDescGZIP(), []int{0}
}

// Options for the local secondary index (lsi)
type LsiOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name of the lsi the field is a part of
	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	// indicate that the field is the sort key of the lsi, else it's part of the projection
	Sk *bool `protobuf:"varint,3,opt,name=sk" json:"sk,omitempty"`
}

func (x *LsiOptions) Reset() {
	*x = LsiOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddb_v1_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsiOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsiOptions) ProtoMessage() {}

func (x *LsiOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ddb_v1_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsiOptions.ProtoReflect.Descriptor instead.
func (*LsiOptions) Descriptor() ([]byte, []int) {
	return file_ddb_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *LsiOptions) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *LsiOptions) GetSk() bool {
	if x != nil && x.Sk != nil {
		return *x.Sk
	}
	return false
}

// Options for the global secondary index (lsi)
type GsiOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name of the gsi the field is a part of
	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	// indicate that the field is the partition key of the gsi
	Pk *bool `protobuf:"varint,2,opt,name=pk" json:"pk,omitempty"`
	// indicate that the field is the sort key of the gsi
	Sk *bool `protobuf:"varint,3,opt,name=sk" json:"sk,omitempty"`
}

func (x *GsiOptions) Reset() {
	*x = GsiOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddb_v1_options_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GsiOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GsiOptions) ProtoMessage() {}

func (x *GsiOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ddb_v1_options_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GsiOptions.ProtoReflect.Descriptor instead.
func (*GsiOptions) Descriptor() ([]byte, []int) {
	return file_ddb_v1_options_proto_rawDescGZIP(), []int{1}
}

func (x *GsiOptions) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GsiOptions) GetPk() bool {
	if x != nil && x.Pk != nil {
		return *x.Pk
	}
	return false
}

func (x *GsiOptions) GetSk() bool {
	if x != nil && x.Sk != nil {
		return *x.Sk
	}
	return false
}

// FieldOptions presents options to configure fields for DynamoDB
type FieldOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// specify the name of the DynamoDB attribute
	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// indicate that the field represents the item's partition key in the table it is stored
	Pk *bool `protobuf:"varint,2,opt,name=pk" json:"pk,omitempty"`
	// indicate that the field represents the item's sort key in the table it is stored
	Sk *bool `protobuf:"varint,3,opt,name=sk" json:"sk,omitempty"`
	// indicate that the field should be ignored by Dynamo code generation
	Omit *bool `protobuf:"varint,4,opt,name=omit" json:"omit,omitempty"`
	// indicate that the field should be marshalled and unmarshalled from dynamo as a set
	Set *bool `protobuf:"varint,5,opt,name=set" json:"set,omitempty"`
	// allows for embedding the field's value as an encoded json or binary protobuf
	Embed *Encoding `protobuf:"varint,6,opt,name=embed,enum=ddb.v1.Encoding" json:"embed,omitempty"`
	// configure the field as part of an lsi on the table it
	Lsi []*LsiOptions `protobuf:"bytes,8,rep,name=lsi" json:"lsi,omitempty"`
	// configure the field as part of the gsi of a table
	Gsi []*GsiOptions `protobuf:"bytes,9,rep,name=gsi" json:"gsi,omitempty"`
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddb_v1_options_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ddb_v1_options_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_ddb_v1_options_proto_rawDescGZIP(), []int{2}
}

func (x *FieldOptions) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *FieldOptions) GetPk() bool {
	if x != nil && x.Pk != nil {
		return *x.Pk
	}
	return false
}

func (x *FieldOptions) GetSk() bool {
	if x != nil && x.Sk != nil {
		return *x.Sk
	}
	return false
}

func (x *FieldOptions) GetOmit() bool {
	if x != nil && x.Omit != nil {
		return *x.Omit
	}
	return false
}

func (x *FieldOptions) GetSet() bool {
	if x != nil && x.Set != nil {
		return *x.Set
	}
	return false
}

func (x *FieldOptions) GetEmbed() Encoding {
	if x != nil && x.Embed != nil {
		return *x.Embed
	}
	return Encoding_ENCODING_UNSPECIFIED
}

func (x *FieldOptions) GetLsi() []*LsiOptions {
	if x != nil {
		return x.Lsi
	}
	return nil
}

func (x *FieldOptions) GetGsi() []*GsiOptions {
	if x != nil {
		return x.Gsi
	}
	return nil
}

// MessageOptions presents options to configure messages for DynamoDB
type MessageOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// table name in which the message will be stored
	Table []string `protobuf:"bytes,1,rep,name=table" json:"table,omitempty"`
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddb_v1_options_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ddb_v1_options_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_ddb_v1_options_proto_rawDescGZIP(), []int{3}
}

func (x *MessageOptions) GetTable() []string {
	if x != nil {
		return x.Table
	}
	return nil
}

var file_ddb_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         1099,
		Name:          "ddb.v1.msg",
		Tag:           "bytes,1099,opt,name=msg",
		Filename:      "ddb/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         1099,
		Name:          "ddb.v1.field",
		Tag:           "bytes,1099,opt,name=field",
		Filename:      "ddb/v1/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional ddb.v1.MessageOptions msg = 1099;
	E_Msg = &file_ddb_v1_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional ddb.v1.FieldOptions field = 1099;
	E_Field = &file_ddb_v1_options_proto_extTypes[1]
)

var File_ddb_v1_options_proto protoreflect.FileDescriptor

var file_ddb_v1_options_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x64, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x1a, 0x20,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x30, 0x0a, 0x0a, 0x4c, 0x73, 0x69, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x73, 0x6b, 0x22, 0x40, 0x0a, 0x0a, 0x47, 0x73, 0x69, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x70, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x73, 0x6b, 0x22, 0xdc, 0x01, 0x0a, 0x0c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x70, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6b, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x73, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x6d, 0x69,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6f, 0x6d, 0x69, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x73, 0x65, 0x74, 0x12,
	0x26, 0x0a, 0x05, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x64, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x05, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x03, 0x6c, 0x73, 0x69, 0x18, 0x08,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x73,
	0x69, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x03, 0x6c, 0x73, 0x69, 0x12, 0x24, 0x0a,
	0x03, 0x67, 0x73, 0x69, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x64, 0x62,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x73, 0x69, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x03,
	0x67, 0x73, 0x69, 0x22, 0x26, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2a, 0x4c, 0x0a, 0x08, 0x45,
	0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x4e, 0x43, 0x4f, 0x44,
	0x49, 0x4e, 0x47, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x4e, 0x43, 0x4f, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x4a, 0x53,
	0x4f, 0x4e, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x43, 0x4f, 0x44, 0x49, 0x4e, 0x47,
	0x5f, 0x44, 0x59, 0x4e, 0x41, 0x4d, 0x4f, 0x10, 0x02, 0x3a, 0x4a, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0xcb, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x64, 0x62, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x3a, 0x4a, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xcb, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x42, 0x91, 0x01, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x64, 0x62, 0x2e, 0x76, 0x31,
	0x42, 0x0c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x65,
	0x77, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67,
	0x65, 0x6e, 0x2d, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x6f, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x64, 0x64, 0x62, 0x2f, 0x76, 0x31, 0x3b, 0x64, 0x64, 0x62, 0x76, 0x31, 0xa2, 0x02,
	0x03, 0x44, 0x58, 0x58, 0xaa, 0x02, 0x06, 0x44, 0x64, 0x62, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x06,
	0x44, 0x64, 0x62, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x12, 0x44, 0x64, 0x62, 0x5c, 0x56, 0x31, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x07, 0x44, 0x64,
	0x62, 0x3a, 0x3a, 0x56, 0x31,
}

var (
	file_ddb_v1_options_proto_rawDescOnce sync.Once
	file_ddb_v1_options_proto_rawDescData = file_ddb_v1_options_proto_rawDesc
)

func file_ddb_v1_options_proto_rawDescGZIP() []byte {
	file_ddb_v1_options_proto_rawDescOnce.Do(func() {
		file_ddb_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_ddb_v1_options_proto_rawDescData)
	})
	return file_ddb_v1_options_proto_rawDescData
}

var file_ddb_v1_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ddb_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ddb_v1_options_proto_goTypes = []interface{}{
	(Encoding)(0),                       // 0: ddb.v1.Encoding
	(*LsiOptions)(nil),                  // 1: ddb.v1.LsiOptions
	(*GsiOptions)(nil),                  // 2: ddb.v1.GsiOptions
	(*FieldOptions)(nil),                // 3: ddb.v1.FieldOptions
	(*MessageOptions)(nil),              // 4: ddb.v1.MessageOptions
	(*descriptorpb.MessageOptions)(nil), // 5: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 6: google.protobuf.FieldOptions
}
var file_ddb_v1_options_proto_depIdxs = []int32{
	0, // 0: ddb.v1.FieldOptions.embed:type_name -> ddb.v1.Encoding
	1, // 1: ddb.v1.FieldOptions.lsi:type_name -> ddb.v1.LsiOptions
	2, // 2: ddb.v1.FieldOptions.gsi:type_name -> ddb.v1.GsiOptions
	5, // 3: ddb.v1.msg:extendee -> google.protobuf.MessageOptions
	6, // 4: ddb.v1.field:extendee -> google.protobuf.FieldOptions
	4, // 5: ddb.v1.msg:type_name -> ddb.v1.MessageOptions
	3, // 6: ddb.v1.field:type_name -> ddb.v1.FieldOptions
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	5, // [5:7] is the sub-list for extension type_name
	3, // [3:5] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ddb_v1_options_proto_init() }
func file_ddb_v1_options_proto_init() {
	if File_ddb_v1_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ddb_v1_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsiOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddb_v1_options_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GsiOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddb_v1_options_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddb_v1_options_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ddb_v1_options_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_ddb_v1_options_proto_goTypes,
		DependencyIndexes: file_ddb_v1_options_proto_depIdxs,
		EnumInfos:         file_ddb_v1_options_proto_enumTypes,
		MessageInfos:      file_ddb_v1_options_proto_msgTypes,
		ExtensionInfos:    file_ddb_v1_options_proto_extTypes,
	}.Build()
	File_ddb_v1_options_proto = out.File
	file_ddb_v1_options_proto_rawDesc = nil
	file_ddb_v1_options_proto_goTypes = nil
	file_ddb_v1_options_proto_depIdxs = nil
}
