// Code generated by protoc-gen-dynamodb. DO NOT EDIT.

package ddbv1

import (
	"fmt"
	attributevalue "github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	types "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	ddb "github.com/crewlinker/protoc-gen-dynamodb/ddb"
)

// MarshalDynamoItem marshals dat into a dynamodb attribute map
func (x *FieldOptions) MarshalDynamoItem() (m map[string]types.AttributeValue, err error) {
	m = make(map[string]types.AttributeValue)
	if x.Name != nil {
		m["1"], err = attributevalue.Marshal(x.GetName())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Name': %w", err)
		}
	}
	if x.Pk != nil {
		m["2"], err = attributevalue.Marshal(x.GetPk())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Pk': %w", err)
		}
	}
	if x.Sk != nil {
		m["3"], err = attributevalue.Marshal(x.GetSk())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Sk': %w", err)
		}
	}
	return m, nil
}

// UnmarshalDynamoItem unmarshals data from a dynamodb attribute map
func (x *FieldOptions) UnmarshalDynamoItem(m map[string]types.AttributeValue) (err error) {
	err = attributevalue.Unmarshal(m["1"], &x.Name)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Name': %w", err)
	}
	err = attributevalue.Unmarshal(m["2"], &x.Pk)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Pk': %w", err)
	}
	err = attributevalue.Unmarshal(m["3"], &x.Sk)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Sk': %w", err)
	}
	return nil
}

// FieldOptionsPath allows for constructing type-safe expression names
type FieldOptionsPath struct {
	ddb.Path
}

func (x *FieldOptions) DynamoPath() FieldOptionsPath {
	return FieldOptionsPath{ddb.Path{}}
}
func (p FieldOptionsPath) Name() ddb.Path {
	return p.Append("1")
}
func (p FieldOptionsPath) Pk() ddb.Path {
	return p.Append("2")
}
func (p FieldOptionsPath) Sk() ddb.Path {
	return p.Append("3")
}
