// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: ddb/v1/options.proto

package ddbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FieldOptions presents options to configure fields to interact with protobuf powered rpc
type FieldOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// specify the name of the DynamoDB attribute
	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// indicate that the field represents the item's partition key
	Pk *bool `protobuf:"varint,2,opt,name=pk" json:"pk,omitempty"`
	// indicate that the field represents the item's sort key
	Sk *bool `protobuf:"varint,3,opt,name=sk" json:"sk,omitempty"`
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddb_v1_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ddb_v1_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_ddb_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *FieldOptions) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *FieldOptions) GetPk() bool {
	if x != nil && x.Pk != nil {
		return *x.Pk
	}
	return false
}

func (x *FieldOptions) GetSk() bool {
	if x != nil && x.Sk != nil {
		return *x.Sk
	}
	return false
}

var file_ddb_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         1098,
		Name:          "ddb.v1.field",
		Tag:           "bytes,1098,opt,name=field",
		Filename:      "ddb/v1/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional ddb.v1.FieldOptions field = 1098;
	E_Field = &file_ddb_v1_options_proto_extTypes[0]
)

var File_ddb_v1_options_proto protoreflect.FileDescriptor

var file_ddb_v1_options_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x64, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x1a, 0x20,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x42, 0x0a, 0x0c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x70, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x73, 0x6b, 0x3a, 0x4a, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xca, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x42, 0x91, 0x01, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x42,
	0x0c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x65, 0x77,
	0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65,
	0x6e, 0x2d, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x6f, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x64, 0x64, 0x62, 0x2f, 0x76, 0x31, 0x3b, 0x64, 0x64, 0x62, 0x76, 0x31, 0xa2, 0x02, 0x03,
	0x44, 0x58, 0x58, 0xaa, 0x02, 0x06, 0x44, 0x64, 0x62, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x06, 0x44,
	0x64, 0x62, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x12, 0x44, 0x64, 0x62, 0x5c, 0x56, 0x31, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x07, 0x44, 0x64, 0x62,
	0x3a, 0x3a, 0x56, 0x31,
}

var (
	file_ddb_v1_options_proto_rawDescOnce sync.Once
	file_ddb_v1_options_proto_rawDescData = file_ddb_v1_options_proto_rawDesc
)

func file_ddb_v1_options_proto_rawDescGZIP() []byte {
	file_ddb_v1_options_proto_rawDescOnce.Do(func() {
		file_ddb_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_ddb_v1_options_proto_rawDescData)
	})
	return file_ddb_v1_options_proto_rawDescData
}

var file_ddb_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ddb_v1_options_proto_goTypes = []interface{}{
	(*FieldOptions)(nil),              // 0: ddb.v1.FieldOptions
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_ddb_v1_options_proto_depIdxs = []int32{
	1, // 0: ddb.v1.field:extendee -> google.protobuf.FieldOptions
	0, // 1: ddb.v1.field:type_name -> ddb.v1.FieldOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ddb_v1_options_proto_init() }
func file_ddb_v1_options_proto_init() {
	if File_ddb_v1_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ddb_v1_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ddb_v1_options_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_ddb_v1_options_proto_goTypes,
		DependencyIndexes: file_ddb_v1_options_proto_depIdxs,
		MessageInfos:      file_ddb_v1_options_proto_msgTypes,
		ExtensionInfos:    file_ddb_v1_options_proto_extTypes,
	}.Build()
	File_ddb_v1_options_proto = out.File
	file_ddb_v1_options_proto_rawDesc = nil
	file_ddb_v1_options_proto_goTypes = nil
	file_ddb_v1_options_proto_depIdxs = nil
}
