// Code generated by protoc-gen-dynamodb. DO NOT EDIT.

// Package messagev1ddb holds generated schema structure
package messagev1ddb

import expression "github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"

// OtherKitchen allows for constructing type-safe expression names
type OtherKitchen struct {
	expression.NameBuilder
}

// WithDynamoNameBuilder allows generic types to overwrite the path
func (p OtherKitchen) WithDynamoNameBuilder(n expression.NameBuilder) OtherKitchen {
	p.NameBuilder = n
	return p
}

// AnotherKitchen returns 'p' with the attribute name appended and allow subselecting nested message
func (p OtherKitchen) AnotherKitchen() Kitchen {
	return Kitchen{p.AppendName(expression.Name("16"))}
}

// OtherTimer appends the path being build
func (p OtherKitchen) OtherTimer() expression.NameBuilder {
	return p.AppendName(expression.Name("17"))
}
