// Code generated by protoc-gen-dynamodb. DO NOT EDIT.

package messagev1

import (
	"fmt"
	attributevalue "github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	types "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	ddb "github.com/crewlinker/protoc-gen-dynamodb/ddb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	"strconv"
)

// MarshalDynamoItem marshals dat into a dynamodb attribute map
func (x *Engine) MarshalDynamoItem(o ...ddb.EncodingOption) (m map[string]types.AttributeValue, err error) {
	m = make(map[string]types.AttributeValue)
	eo := ddb.ApplyEncodingOptions(o...)
	if x.Brand != "" && eo.IsMasked("1") {
		m["1"], err = attributevalue.Marshal(x.GetBrand())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Brand': %w", err)
		}
	}
	if x.Dirtyness != 0 && eo.IsMasked("2") {
		m["2"], err = attributevalue.Marshal(x.GetDirtyness())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Dirtyness': %w", err)
		}
	}
	return m, nil
}

// UnmarshalDynamoItem unmarshals data from a dynamodb attribute map
func (x *Engine) UnmarshalDynamoItem(m map[string]types.AttributeValue, o ...ddb.DecodingOption) (err error) {
	err = attributevalue.Unmarshal(m["1"], &x.Brand)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Brand': %w", err)
	}
	err = attributevalue.Unmarshal(m["2"], &x.Dirtyness)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Dirtyness': %w", err)
	}
	return nil
}

// PartitionKey returns the name of the Dynamo attribute that holds th partition key and the current value of that key in the struct
func (x *Car) PartitionKey() (name string, value int64) {
	return "ws", x.NrOfWheels
}

// Sortkey returns the name of the Dynamo attribute that holds the sort key and the current value of that key in the struct
func (x *Car) SortKey() (name string, value string) {
	return "2", x.Name
}

// MarshalDynamoKey encodes only the item's key attributes into a DynamoDB attribute map
func (x *Car) MarshalDynamoKey() (m map[string]types.AttributeValue, err error) {
	m = make(map[string]types.AttributeValue)
	pk, pkv := x.PartitionKey()
	m[pk], err = attributevalue.Marshal(pkv)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal partition key field: %w", err)
	}
	sk, skv := x.SortKey()
	m[sk], err = attributevalue.Marshal(skv)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal sort key field: %w", err)
	}
	return
}

// MarshalDynamoItem marshals dat into a dynamodb attribute map
func (x *Car) MarshalDynamoItem(o ...ddb.EncodingOption) (m map[string]types.AttributeValue, err error) {
	m = make(map[string]types.AttributeValue)
	eo := ddb.ApplyEncodingOptions(o...)
	if x.Engine != nil && eo.IsMasked("1") {
		m1, err := ddb.MarshalDynamoMessage(x.GetEngine(), ddb.WithEncodingOptions(eo.SubMask("1")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Engine': %w", err)
		}
		m["1"] = m1
	}
	if x.NrOfWheels != 0 && eo.IsMasked("ws") {
		m["ws"], err = attributevalue.Marshal(x.GetNrOfWheels())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'NrOfWheels': %w", err)
		}
	}
	if x.Name != "" && eo.IsMasked("2") {
		m["2"], err = attributevalue.Marshal(x.GetName())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Name': %w", err)
		}
	}
	return m, nil
}

// UnmarshalDynamoItem unmarshals data from a dynamodb attribute map
func (x *Car) UnmarshalDynamoItem(m map[string]types.AttributeValue, o ...ddb.DecodingOption) (err error) {
	if m["1"] != nil {
		x.Engine = new(Engine)
		err = ddb.UnmarshalDynamoMessage(m["1"], x.Engine, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'Engine': %w", err)
		}
	}
	err = attributevalue.Unmarshal(m["ws"], &x.NrOfWheels)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'NrOfWheels': %w", err)
	}
	err = attributevalue.Unmarshal(m["2"], &x.Name)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Name': %w", err)
	}
	return nil
}

// MarshalDynamoItem marshals dat into a dynamodb attribute map
func (x *Appliance) MarshalDynamoItem(o ...ddb.EncodingOption) (m map[string]types.AttributeValue, err error) {
	m = make(map[string]types.AttributeValue)
	eo := ddb.ApplyEncodingOptions(o...)
	if x.Brand != "" && eo.IsMasked("1") {
		m["1"], err = attributevalue.Marshal(x.GetBrand())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Brand': %w", err)
		}
	}
	return m, nil
}

// UnmarshalDynamoItem unmarshals data from a dynamodb attribute map
func (x *Appliance) UnmarshalDynamoItem(m map[string]types.AttributeValue, o ...ddb.DecodingOption) (err error) {
	err = attributevalue.Unmarshal(m["1"], &x.Brand)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Brand': %w", err)
	}
	return nil
}

// PartitionKey returns the name of the Dynamo attribute that holds th partition key and the current value of that key in the struct
func (x *Kitchen) PartitionKey() (name string, value string) {
	return "1", x.Brand
}

// Sortkey returns the name of the Dynamo attribute that holds the sort key and the current value of that key in the struct
func (x *Kitchen) SortKey() (name string, value []byte) {
	return "3", x.QrCode
}

// MarshalDynamoKey encodes only the item's key attributes into a DynamoDB attribute map
func (x *Kitchen) MarshalDynamoKey() (m map[string]types.AttributeValue, err error) {
	m = make(map[string]types.AttributeValue)
	pk, pkv := x.PartitionKey()
	m[pk], err = attributevalue.Marshal(pkv)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal partition key field: %w", err)
	}
	sk, skv := x.SortKey()
	m[sk], err = attributevalue.Marshal(skv)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal sort key field: %w", err)
	}
	return
}

// MarshalDynamoItem marshals dat into a dynamodb attribute map
func (x *Kitchen) MarshalDynamoItem(o ...ddb.EncodingOption) (m map[string]types.AttributeValue, err error) {
	m = make(map[string]types.AttributeValue)
	eo := ddb.ApplyEncodingOptions(o...)
	if x.Brand != "" && eo.IsMasked("1") {
		m["1"], err = attributevalue.Marshal(x.GetBrand())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Brand': %w", err)
		}
	}
	if x.IsRenovated != false && eo.IsMasked("2") {
		m["2"], err = attributevalue.Marshal(x.GetIsRenovated())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'IsRenovated': %w", err)
		}
	}
	if x.QrCode != nil && eo.IsMasked("3") {
		m["3"], err = attributevalue.Marshal(x.GetQrCode())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'QrCode': %w", err)
		}
	}
	if x.NumSmallKnifes != 0 && eo.IsMasked("4") {
		m["4"], err = attributevalue.Marshal(x.GetNumSmallKnifes())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'NumSmallKnifes': %w", err)
		}
	}
	if x.NumSharpKnifes != 0 && eo.IsMasked("5") {
		m["5"], err = attributevalue.Marshal(x.GetNumSharpKnifes())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'NumSharpKnifes': %w", err)
		}
	}
	if x.NumBluntKnifes != 0 && eo.IsMasked("6") {
		m["6"], err = attributevalue.Marshal(x.GetNumBluntKnifes())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'NumBluntKnifes': %w", err)
		}
	}
	if x.NumSmallForks != 0 && eo.IsMasked("7") {
		m["7"], err = attributevalue.Marshal(x.GetNumSmallForks())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'NumSmallForks': %w", err)
		}
	}
	if x.NumMediumForks != 0 && eo.IsMasked("8") {
		m["8"], err = attributevalue.Marshal(x.GetNumMediumForks())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'NumMediumForks': %w", err)
		}
	}
	if x.NumLargeForks != 0 && eo.IsMasked("9") {
		m["9"], err = attributevalue.Marshal(x.GetNumLargeForks())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'NumLargeForks': %w", err)
		}
	}
	if x.PercentBlackTiles != 0 && eo.IsMasked("10") {
		m["10"], err = attributevalue.Marshal(x.GetPercentBlackTiles())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'PercentBlackTiles': %w", err)
		}
	}
	if x.PercentWhiteTiles != 0 && eo.IsMasked("11") {
		m["11"], err = attributevalue.Marshal(x.GetPercentWhiteTiles())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'PercentWhiteTiles': %w", err)
		}
	}
	if x.Dirtyness != 0 && eo.IsMasked("12") {
		m["12"], err = attributevalue.Marshal(x.GetDirtyness())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Dirtyness': %w", err)
		}
	}
	if len(x.Furniture) != 0 && eo.IsMasked("13") {
		m13 := &types.AttributeValueMemberM{Value: make(map[string]types.AttributeValue)}
		for k, v := range x.Furniture {
			mk := fmt.Sprintf("%d", k)
			if mk == "" {
				return nil, fmt.Errorf("failed to marshal map key of field 'Furniture': map key cannot be empty")
			}
			if v == nil {
				m13.Value[mk] = &types.AttributeValueMemberNULL{Value: true}
				continue
			}
			mv, err := ddb.MarshalDynamoMessage(v, ddb.WithEncodingOptions(eo.SubMask("13")))
			if err != nil {
				return nil, fmt.Errorf("failed to marshal map value of field 'Furniture': %w", err)
			}
			m13.Value[mk] = mv
		}
		m["13"] = m13
	}
	if len(x.Calendar) != 0 && eo.IsMasked("14") {
		m["14"], err = attributevalue.Marshal(x.GetCalendar())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Calendar': %w", err)
		}
	}
	if x.WasherEngine != nil && eo.IsMasked("15") {
		m15, err := ddb.MarshalDynamoMessage(x.GetWasherEngine(), ddb.WithEncodingOptions(eo.SubMask("15")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'WasherEngine': %w", err)
		}
		m["15"] = m15
	}
	if x.ExtraKitchen != nil && eo.IsMasked("16") {
		m16, err := ddb.MarshalDynamoMessage(x.GetExtraKitchen(), ddb.WithEncodingOptions(eo.SubMask("16")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'ExtraKitchen': %w", err)
		}
		m["16"] = m16
	}
	if x.Timer != nil && eo.IsMasked("17") {
		m17, err := ddb.MarshalDynamoMessage(x.GetTimer(), ddb.WithEncodingOptions(eo.SubMask("17")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Timer': %w", err)
		}
		m["17"] = m17
	}
	if x.WallTime != nil && eo.IsMasked("18") {
		m18, err := ddb.MarshalDynamoMessage(x.GetWallTime(), ddb.WithEncodingOptions(eo.SubMask("18")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'WallTime': %w", err)
		}
		m["18"] = m18
	}
	if len(x.ApplianceEngines) != 0 && eo.IsMasked("19") {
		m19 := &types.AttributeValueMemberL{}
		for k, v := range x.ApplianceEngines {
			if v == nil {
				m19.Value = append(m19.Value, &types.AttributeValueMemberNULL{Value: true})
				continue
			}
			mv, err := ddb.MarshalDynamoMessage(v, ddb.WithEncodingOptions(eo.SubMask("19")))
			if err != nil {
				return nil, fmt.Errorf("failed to marshal item '%d' of field 'ApplianceEngines': %w", k, err)
			}
			m19.Value = append(m19.Value, mv)
		}
		m["19"] = m19
	}
	if len(x.OtherBrands) != 0 && eo.IsMasked("20") {
		m["20"], err = attributevalue.Marshal(x.GetOtherBrands())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'OtherBrands': %w", err)
		}
	}
	if x.SomeAny != nil && eo.IsMasked("21") {
		m21, err := ddb.MarshalDynamoMessage(x.GetSomeAny(), ddb.WithEncodingOptions(eo.SubMask("21")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'SomeAny': %w", err)
		}
		m["21"] = m21
	}
	if x.SomeMask != nil && eo.IsMasked("22") {
		m22, err := ddb.MarshalDynamoMessage(x.GetSomeMask(), ddb.WithEncodingOptions(eo.SubMask("22")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'SomeMask': %w", err)
		}
		m["22"] = m22
	}
	if x.SomeValue != nil && eo.IsMasked("23") {
		m23, err := ddb.MarshalDynamoMessage(x.GetSomeValue(), ddb.WithEncodingOptions(eo.SubMask("23")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'SomeValue': %w", err)
		}
		m["23"] = m23
	}
	if x.OptString != nil && eo.IsMasked("24") {
		m["24"], err = attributevalue.Marshal(x.GetOptString())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'OptString': %w", err)
		}
	}
	if x.ValStr != nil && eo.IsMasked("25") {
		m25, err := ddb.MarshalDynamoMessage(x.GetValStr(), ddb.WithEncodingOptions(eo.SubMask("25")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'ValStr': %w", err)
		}
		m["25"] = m25
	}
	if x.ValBytes != nil && eo.IsMasked("26") {
		m26, err := ddb.MarshalDynamoMessage(x.GetValBytes(), ddb.WithEncodingOptions(eo.SubMask("26")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'ValBytes': %w", err)
		}
		m["26"] = m26
	}
	return m, nil
}

// UnmarshalDynamoItem unmarshals data from a dynamodb attribute map
func (x *Kitchen) UnmarshalDynamoItem(m map[string]types.AttributeValue, o ...ddb.DecodingOption) (err error) {
	err = attributevalue.Unmarshal(m["1"], &x.Brand)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Brand': %w", err)
	}
	err = attributevalue.Unmarshal(m["2"], &x.IsRenovated)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'IsRenovated': %w", err)
	}
	err = attributevalue.Unmarshal(m["3"], &x.QrCode)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'QrCode': %w", err)
	}
	err = attributevalue.Unmarshal(m["4"], &x.NumSmallKnifes)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'NumSmallKnifes': %w", err)
	}
	err = attributevalue.Unmarshal(m["5"], &x.NumSharpKnifes)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'NumSharpKnifes': %w", err)
	}
	err = attributevalue.Unmarshal(m["6"], &x.NumBluntKnifes)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'NumBluntKnifes': %w", err)
	}
	err = attributevalue.Unmarshal(m["7"], &x.NumSmallForks)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'NumSmallForks': %w", err)
	}
	err = attributevalue.Unmarshal(m["8"], &x.NumMediumForks)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'NumMediumForks': %w", err)
	}
	err = attributevalue.Unmarshal(m["9"], &x.NumLargeForks)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'NumLargeForks': %w", err)
	}
	err = attributevalue.Unmarshal(m["10"], &x.PercentBlackTiles)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'PercentBlackTiles': %w", err)
	}
	err = attributevalue.Unmarshal(m["11"], &x.PercentWhiteTiles)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'PercentWhiteTiles': %w", err)
	}
	err = attributevalue.Unmarshal(m["12"], &x.Dirtyness)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Dirtyness': %w", err)
	}
	if m["13"] != nil {
		x.Furniture = make(map[int64]*Appliance)
		m13, ok := m["13"].(*types.AttributeValueMemberM)
		if !ok {
			return fmt.Errorf("failed to unmarshal field 'Furniture': no map attribute provided")
		}
		for k, v := range m13.Value {
			mk, err := strconv.ParseInt(k, 10, 64)
			if err != nil {
				return fmt.Errorf("failed to unmarshal map key for field 'Furniture': %w", err)
			}
			if _, ok := v.(*types.AttributeValueMemberNULL); ok {
				x.Furniture[int64(mk)] = nil
				continue
			}
			var mv Appliance
			err = ddb.UnmarshalDynamoMessage(v, &mv, o...)
			if err != nil {
				return fmt.Errorf("failed to unmarshal map value for field 'Furniture': %w", err)
			}
			x.Furniture[int64(mk)] = &mv
		}
	}
	err = attributevalue.Unmarshal(m["14"], &x.Calendar)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Calendar': %w", err)
	}
	if m["15"] != nil {
		x.WasherEngine = new(Engine)
		err = ddb.UnmarshalDynamoMessage(m["15"], x.WasherEngine, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'WasherEngine': %w", err)
		}
	}
	if m["16"] != nil {
		x.ExtraKitchen = new(Kitchen)
		err = ddb.UnmarshalDynamoMessage(m["16"], x.ExtraKitchen, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'ExtraKitchen': %w", err)
		}
	}
	if m["17"] != nil {
		x.Timer = new(durationpb.Duration)
		err = ddb.UnmarshalDynamoMessage(m["17"], x.Timer, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'Timer': %w", err)
		}
	}
	if m["18"] != nil {
		x.WallTime = new(timestamppb.Timestamp)
		err = ddb.UnmarshalDynamoMessage(m["18"], x.WallTime, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'WallTime': %w", err)
		}
	}
	if m["19"] != nil {
		m19, ok := m["19"].(*types.AttributeValueMemberL)
		if !ok {
			return fmt.Errorf("failed to unmarshal field 'ApplianceEngines': no list attribute provided")
		}
		for k, v := range m19.Value {
			if _, ok := v.(*types.AttributeValueMemberNULL); ok {
				x.ApplianceEngines = append(x.ApplianceEngines, nil)
				continue
			}
			var mv Engine
			err = ddb.UnmarshalDynamoMessage(v, &mv, o...)
			if err != nil {
				return fmt.Errorf("failed to unmarshal item '%d' of field 'ApplianceEngines': %w", k, err)
			}
			x.ApplianceEngines = append(x.ApplianceEngines, &mv)
		}
	}
	err = attributevalue.Unmarshal(m["20"], &x.OtherBrands)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'OtherBrands': %w", err)
	}
	if m["21"] != nil {
		x.SomeAny = new(anypb.Any)
		err = ddb.UnmarshalDynamoMessage(m["21"], x.SomeAny, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'SomeAny': %w", err)
		}
	}
	if m["22"] != nil {
		x.SomeMask = new(fieldmaskpb.FieldMask)
		err = ddb.UnmarshalDynamoMessage(m["22"], x.SomeMask, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'SomeMask': %w", err)
		}
	}
	if m["23"] != nil {
		x.SomeValue = new(structpb.Value)
		err = ddb.UnmarshalDynamoMessage(m["23"], x.SomeValue, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'SomeValue': %w", err)
		}
	}
	err = attributevalue.Unmarshal(m["24"], &x.OptString)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'OptString': %w", err)
	}
	if m["25"] != nil {
		x.ValStr = new(wrapperspb.StringValue)
		err = ddb.UnmarshalDynamoMessage(m["25"], x.ValStr, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'ValStr': %w", err)
		}
	}
	if m["26"] != nil {
		x.ValBytes = new(wrapperspb.BytesValue)
		err = ddb.UnmarshalDynamoMessage(m["26"], x.ValBytes, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'ValBytes': %w", err)
		}
	}
	return nil
}

// MarshalDynamoItem marshals dat into a dynamodb attribute map
func (x *Empty) MarshalDynamoItem(o ...ddb.EncodingOption) (m map[string]types.AttributeValue, err error) {
	m = make(map[string]types.AttributeValue)
	return m, nil
}

// UnmarshalDynamoItem unmarshals data from a dynamodb attribute map
func (x *Empty) UnmarshalDynamoItem(m map[string]types.AttributeValue, o ...ddb.DecodingOption) (err error) {
	return nil
}

// MarshalDynamoItem marshals dat into a dynamodb attribute map
func (x *MapGalore) MarshalDynamoItem(o ...ddb.EncodingOption) (m map[string]types.AttributeValue, err error) {
	m = make(map[string]types.AttributeValue)
	eo := ddb.ApplyEncodingOptions(o...)
	if len(x.Int64Int64) != 0 && eo.IsMasked("1") {
		m["1"], err = attributevalue.Marshal(x.GetInt64Int64())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Int64Int64': %w", err)
		}
	}
	if len(x.Uint64Uint64) != 0 && eo.IsMasked("2") {
		m["2"], err = attributevalue.Marshal(x.GetUint64Uint64())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Uint64Uint64': %w", err)
		}
	}
	if len(x.Fixed64Fixed64) != 0 && eo.IsMasked("3") {
		m["3"], err = attributevalue.Marshal(x.GetFixed64Fixed64())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Fixed64Fixed64': %w", err)
		}
	}
	if len(x.Sint64Sint64) != 0 && eo.IsMasked("4") {
		m["4"], err = attributevalue.Marshal(x.GetSint64Sint64())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Sint64Sint64': %w", err)
		}
	}
	if len(x.Sfixed64Sfixed64) != 0 && eo.IsMasked("5") {
		m["5"], err = attributevalue.Marshal(x.GetSfixed64Sfixed64())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Sfixed64Sfixed64': %w", err)
		}
	}
	if len(x.Int32Int32) != 0 && eo.IsMasked("6") {
		m["6"], err = attributevalue.Marshal(x.GetInt32Int32())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Int32Int32': %w", err)
		}
	}
	if len(x.Uint32Uint32) != 0 && eo.IsMasked("7") {
		m["7"], err = attributevalue.Marshal(x.GetUint32Uint32())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Uint32Uint32': %w", err)
		}
	}
	if len(x.Fixed32Fixed32) != 0 && eo.IsMasked("8") {
		m["8"], err = attributevalue.Marshal(x.GetFixed32Fixed32())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Fixed32Fixed32': %w", err)
		}
	}
	if len(x.Sint32Sint32) != 0 && eo.IsMasked("9") {
		m["9"], err = attributevalue.Marshal(x.GetSint32Sint32())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Sint32Sint32': %w", err)
		}
	}
	if len(x.Sfixed32Sfixed32) != 0 && eo.IsMasked("10") {
		m["10"], err = attributevalue.Marshal(x.GetSfixed32Sfixed32())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Sfixed32Sfixed32': %w", err)
		}
	}
	if len(x.Stringstring) != 0 && eo.IsMasked("11") {
		m["11"], err = attributevalue.Marshal(x.GetStringstring())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Stringstring': %w", err)
		}
	}
	if len(x.Boolbool) != 0 && eo.IsMasked("12") {
		m["12"], err = attributevalue.Marshal(x.GetBoolbool())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Boolbool': %w", err)
		}
	}
	if len(x.Stringbytes) != 0 && eo.IsMasked("13") {
		m["13"], err = attributevalue.Marshal(x.GetStringbytes())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Stringbytes': %w", err)
		}
	}
	if len(x.Stringdouble) != 0 && eo.IsMasked("14") {
		m["14"], err = attributevalue.Marshal(x.GetStringdouble())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Stringdouble': %w", err)
		}
	}
	if len(x.Stringfloat) != 0 && eo.IsMasked("15") {
		m["15"], err = attributevalue.Marshal(x.GetStringfloat())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Stringfloat': %w", err)
		}
	}
	if len(x.Stringduration) != 0 && eo.IsMasked("16") {
		m16 := &types.AttributeValueMemberM{Value: make(map[string]types.AttributeValue)}
		for k, v := range x.Stringduration {
			mk := k
			if mk == "" {
				return nil, fmt.Errorf("failed to marshal map key of field 'Stringduration': map key cannot be empty")
			}
			if v == nil {
				m16.Value[mk] = &types.AttributeValueMemberNULL{Value: true}
				continue
			}
			mv, err := ddb.MarshalDynamoMessage(v, ddb.WithEncodingOptions(eo.SubMask("16")))
			if err != nil {
				return nil, fmt.Errorf("failed to marshal map value of field 'Stringduration': %w", err)
			}
			m16.Value[mk] = mv
		}
		m["16"] = m16
	}
	if len(x.Stringtimestamp) != 0 && eo.IsMasked("17") {
		m17 := &types.AttributeValueMemberM{Value: make(map[string]types.AttributeValue)}
		for k, v := range x.Stringtimestamp {
			mk := k
			if mk == "" {
				return nil, fmt.Errorf("failed to marshal map key of field 'Stringtimestamp': map key cannot be empty")
			}
			if v == nil {
				m17.Value[mk] = &types.AttributeValueMemberNULL{Value: true}
				continue
			}
			mv, err := ddb.MarshalDynamoMessage(v, ddb.WithEncodingOptions(eo.SubMask("17")))
			if err != nil {
				return nil, fmt.Errorf("failed to marshal map value of field 'Stringtimestamp': %w", err)
			}
			m17.Value[mk] = mv
		}
		m["17"] = m17
	}
	return m, nil
}

// UnmarshalDynamoItem unmarshals data from a dynamodb attribute map
func (x *MapGalore) UnmarshalDynamoItem(m map[string]types.AttributeValue, o ...ddb.DecodingOption) (err error) {
	err = attributevalue.Unmarshal(m["1"], &x.Int64Int64)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Int64Int64': %w", err)
	}
	err = attributevalue.Unmarshal(m["2"], &x.Uint64Uint64)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Uint64Uint64': %w", err)
	}
	err = attributevalue.Unmarshal(m["3"], &x.Fixed64Fixed64)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Fixed64Fixed64': %w", err)
	}
	err = attributevalue.Unmarshal(m["4"], &x.Sint64Sint64)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Sint64Sint64': %w", err)
	}
	err = attributevalue.Unmarshal(m["5"], &x.Sfixed64Sfixed64)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Sfixed64Sfixed64': %w", err)
	}
	err = attributevalue.Unmarshal(m["6"], &x.Int32Int32)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Int32Int32': %w", err)
	}
	err = attributevalue.Unmarshal(m["7"], &x.Uint32Uint32)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Uint32Uint32': %w", err)
	}
	err = attributevalue.Unmarshal(m["8"], &x.Fixed32Fixed32)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Fixed32Fixed32': %w", err)
	}
	err = attributevalue.Unmarshal(m["9"], &x.Sint32Sint32)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Sint32Sint32': %w", err)
	}
	err = attributevalue.Unmarshal(m["10"], &x.Sfixed32Sfixed32)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Sfixed32Sfixed32': %w", err)
	}
	err = attributevalue.Unmarshal(m["11"], &x.Stringstring)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Stringstring': %w", err)
	}
	err = attributevalue.Unmarshal(m["12"], &x.Boolbool)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Boolbool': %w", err)
	}
	err = attributevalue.Unmarshal(m["13"], &x.Stringbytes)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Stringbytes': %w", err)
	}
	err = attributevalue.Unmarshal(m["14"], &x.Stringdouble)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Stringdouble': %w", err)
	}
	err = attributevalue.Unmarshal(m["15"], &x.Stringfloat)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Stringfloat': %w", err)
	}
	if m["16"] != nil {
		x.Stringduration = make(map[string]*durationpb.Duration)
		m16, ok := m["16"].(*types.AttributeValueMemberM)
		if !ok {
			return fmt.Errorf("failed to unmarshal field 'Stringduration': no map attribute provided")
		}
		for k, v := range m16.Value {
			mk := k
			if _, ok := v.(*types.AttributeValueMemberNULL); ok {
				x.Stringduration[string(mk)] = nil
				continue
			}
			var mv durationpb.Duration
			err = ddb.UnmarshalDynamoMessage(v, &mv, o...)
			if err != nil {
				return fmt.Errorf("failed to unmarshal map value for field 'Stringduration': %w", err)
			}
			x.Stringduration[string(mk)] = &mv
		}
	}
	if m["17"] != nil {
		x.Stringtimestamp = make(map[string]*timestamppb.Timestamp)
		m17, ok := m["17"].(*types.AttributeValueMemberM)
		if !ok {
			return fmt.Errorf("failed to unmarshal field 'Stringtimestamp': no map attribute provided")
		}
		for k, v := range m17.Value {
			mk := k
			if _, ok := v.(*types.AttributeValueMemberNULL); ok {
				x.Stringtimestamp[string(mk)] = nil
				continue
			}
			var mv timestamppb.Timestamp
			err = ddb.UnmarshalDynamoMessage(v, &mv, o...)
			if err != nil {
				return fmt.Errorf("failed to unmarshal map value for field 'Stringtimestamp': %w", err)
			}
			x.Stringtimestamp[string(mk)] = &mv
		}
	}
	return nil
}

// MarshalDynamoItem marshals dat into a dynamodb attribute map
func (x *ValueGalore) MarshalDynamoItem(o ...ddb.EncodingOption) (m map[string]types.AttributeValue, err error) {
	m = make(map[string]types.AttributeValue)
	eo := ddb.ApplyEncodingOptions(o...)
	if x.SomeValue != nil && eo.IsMasked("1") {
		m1, err := ddb.MarshalDynamoMessage(x.GetSomeValue(), ddb.WithEncodingOptions(eo.SubMask("1")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'SomeValue': %w", err)
		}
		m["1"] = m1
	}
	return m, nil
}

// UnmarshalDynamoItem unmarshals data from a dynamodb attribute map
func (x *ValueGalore) UnmarshalDynamoItem(m map[string]types.AttributeValue, o ...ddb.DecodingOption) (err error) {
	if m["1"] != nil {
		x.SomeValue = new(structpb.Value)
		err = ddb.UnmarshalDynamoMessage(m["1"], x.SomeValue, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'SomeValue': %w", err)
		}
	}
	return nil
}

// MarshalDynamoItem marshals dat into a dynamodb attribute map
func (x *FieldPresence) MarshalDynamoItem(o ...ddb.EncodingOption) (m map[string]types.AttributeValue, err error) {
	m = make(map[string]types.AttributeValue)
	eo := ddb.ApplyEncodingOptions(o...)
	if x.Str != "" && eo.IsMasked("str") {
		m["str"], err = attributevalue.Marshal(x.GetStr())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Str': %w", err)
		}
	}
	if x.OptStr != nil && eo.IsMasked("optStr") {
		m["optStr"], err = attributevalue.Marshal(x.GetOptStr())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'OptStr': %w", err)
		}
	}
	if x.Msg != nil && eo.IsMasked("msg") {
		m3, err := ddb.MarshalDynamoMessage(x.GetMsg(), ddb.WithEncodingOptions(eo.SubMask("msg")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Msg': %w", err)
		}
		m["msg"] = m3
	}
	if x.OptMsg != nil && eo.IsMasked("optMsg") {
		m4, err := ddb.MarshalDynamoMessage(x.GetOptMsg(), ddb.WithEncodingOptions(eo.SubMask("optMsg")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'OptMsg': %w", err)
		}
		m["optMsg"] = m4
	}
	if len(x.StrList) != 0 && eo.IsMasked("strList") {
		m["strList"], err = attributevalue.Marshal(x.GetStrList())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'StrList': %w", err)
		}
	}
	if len(x.MsgList) != 0 && eo.IsMasked("msgList") {
		m6 := &types.AttributeValueMemberL{}
		for k, v := range x.MsgList {
			if v == nil {
				m6.Value = append(m6.Value, &types.AttributeValueMemberNULL{Value: true})
				continue
			}
			mv, err := ddb.MarshalDynamoMessage(v, ddb.WithEncodingOptions(eo.SubMask("msgList")))
			if err != nil {
				return nil, fmt.Errorf("failed to marshal item '%d' of field 'MsgList': %w", k, err)
			}
			m6.Value = append(m6.Value, mv)
		}
		m["msgList"] = m6
	}
	if len(x.StrMap) != 0 && eo.IsMasked("strMap") {
		m["strMap"], err = attributevalue.Marshal(x.GetStrMap())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'StrMap': %w", err)
		}
	}
	if len(x.MsgMap) != 0 && eo.IsMasked("msgMap") {
		m8 := &types.AttributeValueMemberM{Value: make(map[string]types.AttributeValue)}
		for k, v := range x.MsgMap {
			mk := k
			if mk == "" {
				return nil, fmt.Errorf("failed to marshal map key of field 'MsgMap': map key cannot be empty")
			}
			if v == nil {
				m8.Value[mk] = &types.AttributeValueMemberNULL{Value: true}
				continue
			}
			mv, err := ddb.MarshalDynamoMessage(v, ddb.WithEncodingOptions(eo.SubMask("msgMap")))
			if err != nil {
				return nil, fmt.Errorf("failed to marshal map value of field 'MsgMap': %w", err)
			}
			m8.Value[mk] = mv
		}
		m["msgMap"] = m8
	}
	if x.Enum != 0 && eo.IsMasked("enum") {
		m["enum"], err = attributevalue.Marshal(x.GetEnum())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Enum': %w", err)
		}
	}
	if x.OptEnum != nil && eo.IsMasked("optEnum") {
		m["optEnum"], err = attributevalue.Marshal(x.GetOptEnum())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'OptEnum': %w", err)
		}
	}
	if onev, ok := x.Oo.(*FieldPresence_OneofStr); ok && onev != nil && eo.IsMasked("oneofStr") {
		m["oneofStr"], err = attributevalue.Marshal(x.GetOneofStr())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'OneofStr': %w", err)
		}
	}
	if onev, ok := x.Oo.(*FieldPresence_OneofMsg); ok && onev != nil && eo.IsMasked("oneofMsg") {
		m12, err := ddb.MarshalDynamoMessage(x.GetOneofMsg(), ddb.WithEncodingOptions(eo.SubMask("oneofMsg")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'OneofMsg': %w", err)
		}
		m["oneofMsg"] = m12
	}
	if x.StrVal != nil && eo.IsMasked("strVal") {
		m13, err := ddb.MarshalDynamoMessage(x.GetStrVal(), ddb.WithEncodingOptions(eo.SubMask("strVal")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'StrVal': %w", err)
		}
		m["strVal"] = m13
	}
	if x.BoolVal != nil && eo.IsMasked("boolVal") {
		m14, err := ddb.MarshalDynamoMessage(x.GetBoolVal(), ddb.WithEncodingOptions(eo.SubMask("boolVal")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'BoolVal': %w", err)
		}
		m["boolVal"] = m14
	}
	if x.BytesVal != nil && eo.IsMasked("bytesVal") {
		m15, err := ddb.MarshalDynamoMessage(x.GetBytesVal(), ddb.WithEncodingOptions(eo.SubMask("bytesVal")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'BytesVal': %w", err)
		}
		m["bytesVal"] = m15
	}
	if x.DoubleVal != nil && eo.IsMasked("doubleVal") {
		m16, err := ddb.MarshalDynamoMessage(x.GetDoubleVal(), ddb.WithEncodingOptions(eo.SubMask("doubleVal")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'DoubleVal': %w", err)
		}
		m["doubleVal"] = m16
	}
	if x.FloatVal != nil && eo.IsMasked("floatVal") {
		m17, err := ddb.MarshalDynamoMessage(x.GetFloatVal(), ddb.WithEncodingOptions(eo.SubMask("floatVal")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'FloatVal': %w", err)
		}
		m["floatVal"] = m17
	}
	if x.Int32Val != nil && eo.IsMasked("int32Val") {
		m18, err := ddb.MarshalDynamoMessage(x.GetInt32Val(), ddb.WithEncodingOptions(eo.SubMask("int32Val")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Int32Val': %w", err)
		}
		m["int32Val"] = m18
	}
	if x.Int64Val != nil && eo.IsMasked("int64Val") {
		m19, err := ddb.MarshalDynamoMessage(x.GetInt64Val(), ddb.WithEncodingOptions(eo.SubMask("int64Val")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Int64Val': %w", err)
		}
		m["int64Val"] = m19
	}
	if x.Uint32Val != nil && eo.IsMasked("uint32Val") {
		m20, err := ddb.MarshalDynamoMessage(x.GetUint32Val(), ddb.WithEncodingOptions(eo.SubMask("uint32Val")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Uint32Val': %w", err)
		}
		m["uint32Val"] = m20
	}
	if x.Uint64Val != nil && eo.IsMasked("uint64Val") {
		m21, err := ddb.MarshalDynamoMessage(x.GetUint64Val(), ddb.WithEncodingOptions(eo.SubMask("uint64Val")))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal field 'Uint64Val': %w", err)
		}
		m["uint64Val"] = m21
	}
	return m, nil
}

// UnmarshalDynamoItem unmarshals data from a dynamodb attribute map
func (x *FieldPresence) UnmarshalDynamoItem(m map[string]types.AttributeValue, o ...ddb.DecodingOption) (err error) {
	err = attributevalue.Unmarshal(m["str"], &x.Str)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Str': %w", err)
	}
	err = attributevalue.Unmarshal(m["optStr"], &x.OptStr)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'OptStr': %w", err)
	}
	if m["msg"] != nil {
		x.Msg = new(Engine)
		err = ddb.UnmarshalDynamoMessage(m["msg"], x.Msg, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'Msg': %w", err)
		}
	}
	if m["optMsg"] != nil {
		x.OptMsg = new(Engine)
		err = ddb.UnmarshalDynamoMessage(m["optMsg"], x.OptMsg, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'OptMsg': %w", err)
		}
	}
	err = attributevalue.Unmarshal(m["strList"], &x.StrList)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'StrList': %w", err)
	}
	if m["msgList"] != nil {
		m6, ok := m["msgList"].(*types.AttributeValueMemberL)
		if !ok {
			return fmt.Errorf("failed to unmarshal field 'MsgList': no list attribute provided")
		}
		for k, v := range m6.Value {
			if _, ok := v.(*types.AttributeValueMemberNULL); ok {
				x.MsgList = append(x.MsgList, nil)
				continue
			}
			var mv Engine
			err = ddb.UnmarshalDynamoMessage(v, &mv, o...)
			if err != nil {
				return fmt.Errorf("failed to unmarshal item '%d' of field 'MsgList': %w", k, err)
			}
			x.MsgList = append(x.MsgList, &mv)
		}
	}
	err = attributevalue.Unmarshal(m["strMap"], &x.StrMap)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'StrMap': %w", err)
	}
	if m["msgMap"] != nil {
		x.MsgMap = make(map[string]*Engine)
		m8, ok := m["msgMap"].(*types.AttributeValueMemberM)
		if !ok {
			return fmt.Errorf("failed to unmarshal field 'MsgMap': no map attribute provided")
		}
		for k, v := range m8.Value {
			mk := k
			if _, ok := v.(*types.AttributeValueMemberNULL); ok {
				x.MsgMap[string(mk)] = nil
				continue
			}
			var mv Engine
			err = ddb.UnmarshalDynamoMessage(v, &mv, o...)
			if err != nil {
				return fmt.Errorf("failed to unmarshal map value for field 'MsgMap': %w", err)
			}
			x.MsgMap[string(mk)] = &mv
		}
	}
	err = attributevalue.Unmarshal(m["enum"], &x.Enum)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'Enum': %w", err)
	}
	err = attributevalue.Unmarshal(m["optEnum"], &x.OptEnum)
	if err != nil {
		return fmt.Errorf("failed to unmarshal field 'OptEnum': %w", err)
	}
	if m["oneofStr"] != nil {
		var mo FieldPresence_OneofStr
		err = attributevalue.Unmarshal(m["oneofStr"], &mo.OneofStr)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'OneofStr': %w", err)
		}
		x.Oo = &mo
	}
	if m["oneofMsg"] != nil {
		var mo FieldPresence_OneofMsg
		mo.OneofMsg = new(Engine)
		err = ddb.UnmarshalDynamoMessage(m["oneofMsg"], mo.OneofMsg, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'OneofMsg': %w", err)
		}
		x.Oo = &mo
	}
	if m["strVal"] != nil {
		x.StrVal = new(wrapperspb.StringValue)
		err = ddb.UnmarshalDynamoMessage(m["strVal"], x.StrVal, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'StrVal': %w", err)
		}
	}
	if m["boolVal"] != nil {
		x.BoolVal = new(wrapperspb.BoolValue)
		err = ddb.UnmarshalDynamoMessage(m["boolVal"], x.BoolVal, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'BoolVal': %w", err)
		}
	}
	if m["bytesVal"] != nil {
		x.BytesVal = new(wrapperspb.BytesValue)
		err = ddb.UnmarshalDynamoMessage(m["bytesVal"], x.BytesVal, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'BytesVal': %w", err)
		}
	}
	if m["doubleVal"] != nil {
		x.DoubleVal = new(wrapperspb.DoubleValue)
		err = ddb.UnmarshalDynamoMessage(m["doubleVal"], x.DoubleVal, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'DoubleVal': %w", err)
		}
	}
	if m["floatVal"] != nil {
		x.FloatVal = new(wrapperspb.FloatValue)
		err = ddb.UnmarshalDynamoMessage(m["floatVal"], x.FloatVal, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'FloatVal': %w", err)
		}
	}
	if m["int32Val"] != nil {
		x.Int32Val = new(wrapperspb.Int32Value)
		err = ddb.UnmarshalDynamoMessage(m["int32Val"], x.Int32Val, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'Int32Val': %w", err)
		}
	}
	if m["int64Val"] != nil {
		x.Int64Val = new(wrapperspb.Int64Value)
		err = ddb.UnmarshalDynamoMessage(m["int64Val"], x.Int64Val, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'Int64Val': %w", err)
		}
	}
	if m["uint32Val"] != nil {
		x.Uint32Val = new(wrapperspb.UInt32Value)
		err = ddb.UnmarshalDynamoMessage(m["uint32Val"], x.Uint32Val, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'Uint32Val': %w", err)
		}
	}
	if m["uint64Val"] != nil {
		x.Uint64Val = new(wrapperspb.UInt64Value)
		err = ddb.UnmarshalDynamoMessage(m["uint64Val"], x.Uint64Val, o...)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field 'Uint64Val': %w", err)
		}
	}
	return nil
}
