name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.0"
      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install tooling
        run: |
          go install -mod=readonly github.com/magefile/mage
      - name: Lint Protobufs
        uses: bufbuild/buf-lint-action@v1
      - name: Check Protobufs breaking changes
        uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main"
      - name: Run all checks
        run: |
          mage -v checks
      - name: Check code generation was run
        run: |
          mage -v generate
          test -z "$(git status -s)"
